plugins.rst
Generally, it is a bad idea to put "here" as only link-option, as uxmovement's article called ['Why Your Links Should Never Say “Click Here”'](http://uxmovement.com/content/why-your-links-should-never-say-click-here) explains.
Basically, every time I see a "the list is [here]().", I wonder: "Where? There's no list HERE....". I fall for this every time, and I know people that got really frustrated by this.
=> plugins.rst: changed link-text to omv-extras.org from "here" to "omv-extras.org"

administration/general/notifications.rst
Changed name of file /etc/postfix/recipients_canonical to /etc/postfix/recipient_canonical
=> Correct postfix file name

installation/on_debian.rst
It's 2019 year here. It's not safe to get keyring over HTTP without any authentication verification. The Docker approach isn't bad https://docs.docker.com/install/linux/docker-ce/debian/ -- `curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -`
So changing transport of HTTP to HTTPS of APT for OMV will do similar. It's safe.
=> openmediavault-keyring should be downloaded safely

installation/on_debian.rst
It's important to use the tweaked OMV install on ARM if available since otherwise performance sucks: https://forum.armbian.com/topic/3953-preview-generate-omv-images-for-sbc-with-armbian/?do=findComment&comment=44168
=> Different installation procedure for ARM

installation/index.rst
https://dictionary.cambridge.org/dictionary/english/as-a-last-resort
=> Typo: "as a last resort", not "as a last resource"

administration/general/network.rst
Minor changes made to documentation only to deal with spelling and grammar errors, and to improve readability.
Worth checking that the RST for the final tip works with readthedocs, which uses different templates to GitHub.
=> Grammar and spelling improvements.

administration/access_rights_management.rst, administration/general/certificates.rst, administration/general/cron.rst, administration/general/notifications.rst, administration/services/samba.rst, howitworks.rst
Avoid his/he/him pronouns. Other trivial grammar improvements.
=> Use gender-neutral language to describe users.

various/fs_env_vars.rst
Command` omv-mkconf` has been replaced by `omv-salt deploy run` in omv 5.x.  I tested this on my NAS and it worked fine.
=> Replaced outdated omv-mkconf with omv-salt

faq.rst
"Can I backup or restore an existing |omv| configuration?"
The answer began with a "No", but the text then explains a way (to backup config.xml).
Im my view, the answer should start with a tentative "There is no regular backup/restore procedure, but yes, in some way:". My pull request proposes such a change.
=> changing a "no" to tentative "yes"

installation/on_debian.rst
Installation breaks update on Rpi as per https://github.com/openmediavault/openmediavault/issues/849. This may help users end in a better place
=> Point Raspbian users to better place.

README.md
It started serving on port 8080 instead of 8000 for me. I'm on Ubuntu 21.10. Is it the same for everyone else?
=> Corrected the port number where the documentation is hosted locally.

development/contribute.rst
Fixes: https://github.com/openmediavault/openmediavault-docs/issues/108
Signed-off-by: mi-hol 22799428+mi-hol@users.noreply.github.com
=> Align docs with GitHub content for contributing

support.rst
This is to update the discord invite link. The old server is read only now. This is properly maintained and moderated.
Thanks
=> Update discord link

administration/general/notifications.rst
The existing docs described how to use "less secure apps" but this option shut down in 2022 and is no longer available.
=> Updated note about "less secure apps" which is shut down now

installation/on_debian.rst
Prevents garbled output when importing the keyring:
Also, no need to install openmediavault-keyring package specifically since it's an openmediavault package dependency.
=> Minor clean-up

various/advset.rst
... at least, that's what I assume, since my system doesn't have a `/src/` directory, and on line 69 `/srv/` is mentioned, which does exist.
=> Update advset.rst - typo in line 77

administration/users.rst
users and group docs improved with missing informatino fixed #138
* Completed documentation about user management
* described how works user management respect the OS
* described ithe complete management of the users
* removed unnecesary technical information
* completed missing information as #138 
* Better description about fileds to fill at the users/group forms for create/edit actions
* Closed #138 
**NOTE** this pull request can be edited by repository owners, and to avoid too much commit history they can squash it
=> users and group docs improved with missing informatino fixed #138

administration/users.rst
* put the missing context in users rules respect the home directori settings, docs does not mention that is for existing users..
* lack of smooth introduction to GIU, it has been noticed that most who use OMV are Windows users and this is mentioned to them without prior explanation... since they only install the OMV ISO and run commands without knowing the nature of this.
=> minor change, two lines.. lost of context in users, and lack of smooth intro to GIU/UID

plugins.rst
Unlike what the current page says, the FTP server plugin does not provide SFTP (it provides FTP and FTPS), while there is another plugin for FTP. Having a single line misleads users interested in SFTP to install the FTP plugin and wonder how to get SFTP.
=> Update plugins.rst for SFTP

prerequisites.rst
* Addressed and closed #131, requirements talk about installation, not updates (not manageable updates), so the wording is correct because later on there are points about that, but i handled the issue in this commit in better way for.
* Improve the very vague requirements documentation, that is also ambiguous in some way.
* Not all software requirements are handled by the OS, for example we need a valid network for communications, if the network is unreachable clients are unable to reach any shared resources.
* OMV is the most flexible NAS system. Pointed that out and tried to clarify all the needs about hardware and software.
* Separate software requirements and hardware requirements. Previous document was very mixed about it, maybe this commit featured a too long one. I'm open to …
=> requirements docs improved with missing information fixed

development/tools/omv_salt.rst
Add commands that will show which states are dirty, and deploy only the dirty states.
=> omv_salt - add how to see / run dirty states

administration/storage/filesystems.rst
PVE kernel is recommended if using ZFS and should be installed before ZFS plugin in order to avoid problems. Update docs to reflect this. See thread https://forum.openmediavault.org/index.php?thread/55706-problem-with-new-omv7-kernel-update/&postID=414454#post414454
=> Update filesystems.rst to recommend PVE kernel for ZFS
